git:
    submodules: false

branches:
    only:
        -master

notifications:
    email: false

language: generic

before_install:
    - sudo apt update
    - sudo apt install nodejs npm
    - sudo pip install --upgrade pip
    - sudo pip install Sphinx
    - sudo pip install sphinxcontrib-inlinesyntaxhighlight
    - sudo pip install sphinx-sitemap
    - sudo apt install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
    - git clone https://github.com/FreeFem/FreeFem-parser-pygments.git ~/pygments
    - sudo cp ~/pygments/freefem.py /usr/local/lib/python2.7/dist-packages/pygments/lexers/
    - cd /usr/local/lib/python2.7/dist-packages/pygments/lexers/ && sudo python _mapping.py
    - cd /home/travis/build/FreeFem/${GH_REPOSITORY}

script:
    # - SPHINXOPTS='-n -b linkcheck' make -e html
    - make html
    - make latex
    - echo "doc.freefem.org" > build/html/CNAME
    - cd build/latex && DATE=`date +%Y%m%d` && pdflatex -interaction=nonstopmode -jobname FreeFEM-doc_released_${DATE} FreeFEM.tex && pdflatex -interaction=nonstopmode -jobname FreeFEM-doc_released_${DATE} FreeFEM.tex && cd ../..

before_deploy:
    - git config --local user.name "sgarnotel"
    - git config --local user.email "simon.garnotel@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG --force

deploy:
    - provider: pages
      skip-cleanup: true
      github-token: ${GH_TOKEN}
      local-dir: build/html/
      target-branch: gh-pages
      keep-history: true
    - provider: releases
      skip-cleanup: true
      api_key: ${GH_TOKEN}
      file: build/latex/FreeFEM-doc_released_${DATE}.pdf
