sudo: false
language: python
env:
  global:
  - secure: KjUFAszvJ2xoc+VWJpXRuim2v1iJ6nVIE3PheYVOZsECXuRHF9kUnp3neJPzXBL5as5bnbXzcJw6LYcD68SN40iFHQ88oU8mGN3L6uhdo6lNdJnbFyAyEKPZr0kASoGyI3qUKN8VzqYofEvM+rRN7gWGzXziw3rRyolTwRNJ3o533+iQEoXpBMqVJAkEtjm6qm+m945DiCxKAj6NufwN7fTbXuzousjgcwGsYskI8x5czC94d4MlHZ/meOBplVR/xgYSJPA+C7qWpP9OusXR99Zy/Tq19lAulVSZjmfZIv90l+zgrxQwiRTHvzMYKseKRfnZ0uKHzvl5bPXGIMuh1f8BUxqoacpnwGh/eza5xZba7pCoIu6bfYIANAfTvI18i3BKpXCwqj7fAG4EEITj3BuoQyB11hulMe31znMAjfWSAogVtHTF9pekpX27/12rFaLmMWG/WZ+q47kgIBpiN6HZJi5zjJMbsI3I/5G3oLk5A33x7iHgi0T7ll1bv1qNcW9guvusGqZDPzml+Z4HvfvkP59FW+SBh23GQ2IuIaGgZcZ6AG2H+7imOnJKp3Zsy3RIq7NPCJrJE+P3o6tXPh6P9mebScvsj2Sln1AQSmZ56rX+KSJxD/+hpJzaFtr9DUkfJWVbipZ0f87KRgg5Ouq9r7oFU18y19YfNKt0ZLA=
  - secure: B0xKaaV6gNxGStjLYPdkk8v7cvbBQcWG9RWvH3nHSDs0C0Q+uy5BZkC/a1/Xqub4DIdMA53gijMDd5sURhCneufi3VETf3Q+dTLsSijX6fQFGnJOJhXDdPxnicelbWwM4xhxIKJLZXLVuOy+fDuix/lKUDxThj8gKkjGyHOjgvlBeiP+Ewh79f+Ruja0NF5ZWF6PZflUeT8TvpytSUyrvVpn0BU1JfNEq7vrO2jB5BjFs2kAuGImf+BYti7x9tRD517dIFGRLCjeD8m7aejdWTPXDqtdnA5eqSCxxbviSiCljxOaBT14om6TbcfHDEKrovX5/Z/huXIUui3s8eNiRkagHRN6CDYQ/KQ/Ehsco1hGt4BT9bRvTQu/CbuQ0IIITiEo4L80IbZXL7mKt+mhEHZRppOSfleHUSxM1KIdprL+2kKWoVUkpXJWmmQ3asxmjWwuoc3mF3SfifXWRfr1x/uOR9Nv0SyZe7y0RZc585Rgpt+OADc8qm7OsduXI1VuGgbx/KfdRZAglXKDWTUvMRov1BRz3RnJmRKXMPcpoVU6SVxJVY2gmaKUsJl8YGFim2ml8qGbtmbspHQwyHjiwh6gm0iQb0S8lYJvKtcYOTKc34KxtP+C4ZOfCafnA7ryAav+kldEr4gS30zuvifK58DYUNe/N/fv8EsuTz1n6j8=
install:
- pip install mkdocs
- pip install mkdocs-material
- pip install python-markdown-math
script:
- git clean -f -d -x
- mkdocs build
after_success:
- git config user.name "Travis CI"
- git config user.email "contact@airthium.com"
- git remote add gh-token "https://${GH_TOKEN}@github.com/FreeFem/FreeFem-doc.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;
