sudo: false
language: python
env:
  global:
    secure: KjUFAszvJ2xoc+VWJpXRuim2v1iJ6nVIE3PheYVOZsECXuRHF9kUnp3neJPzXBL5as5bnbXzcJw6LYcD68SN40iFHQ88oU8mGN3L6uhdo6lNdJnbFyAyEKPZr0kASoGyI3qUKN8VzqYofEvM+rRN7gWGzXziw3rRyolTwRNJ3o533+iQEoXpBMqVJAkEtjm6qm+m945DiCxKAj6NufwN7fTbXuzousjgcwGsYskI8x5czC94d4MlHZ/meOBplVR/xgYSJPA+C7qWpP9OusXR99Zy/Tq19lAulVSZjmfZIv90l+zgrxQwiRTHvzMYKseKRfnZ0uKHzvl5bPXGIMuh1f8BUxqoacpnwGh/eza5xZba7pCoIu6bfYIANAfTvI18i3BKpXCwqj7fAG4EEITj3BuoQyB11hulMe31znMAjfWSAogVtHTF9pekpX27/12rFaLmMWG/WZ+q47kgIBpiN6HZJi5zjJMbsI3I/5G3oLk5A33x7iHgi0T7ll1bv1qNcW9guvusGqZDPzml+Z4HvfvkP59FW+SBh23GQ2IuIaGgZcZ6AG2H+7imOnJKp3Zsy3RIq7NPCJrJE+P3o6tXPh6P9mebScvsj2Sln1AQSmZ56rX+KSJxD/+hpJzaFtr9DUkfJWVbipZ0f87KRgg5Ouq9r7oFU18y19YfNKt0ZLA=
install:
- pip install mkdocs
- pip install mkdocs-material
- pip install python-markdown-math
script:
- git clean -f -d -x
- mkdocs build
after_success:
- git config user.name "Travis CI"
- git config user.email "contact@airthium.com"
- git remote add gh-token "https://${GH_TOKEN}@github.com/FreeFem/FreeFem-doc.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;
