sudo: false
language: python
install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install python-markdown-math
script:
  - git clean -f -d -x
after_success:
  - git config user.name "Simon Garnotel"
  - git config user.email "simon.garnotel@gmail.com"
  - git remote add gh-token "https://${GH_TOKEN}@github.com/FreeFem/FreeFem-doc.git";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - mkdocs gh-deploy -v --clean --remote-name gh-token;
