sudo: false
language: python
env:
  global:
  - secure: d5ereaBkwS6DXENDbvuhciK7yxLF3s37b65cSoJ9sUUR/VCH4Zqnp2nsp6mxhkdzSJyp3M5+bSkc6Rg8erH5k/MQhHUV8wfnMMH5vR9y1pScHwKgh58+yPccrlBy/kTs2TCkIotTUG4mzMzn0DEaoi/rEZIcyBW16cHtoohwKGS3Q8uT9pCIJ1YTmnbbyfa7VHmmP3ts58gztzsNW93tjuSwAq3cTueb6LDgMx617jeKYxfnPYQRQw8rENPjEiI5qpgJi5V+GjDw9PMFu+mWRdytKtnNdT+C6WqkMRx/voKBNHplMMSN2xfDbsWCBXR+6F7TH0OCiTGkpK6TjU4iHrVfiEQX+6kCE7lyMEUR4N/q45JOnbsS50Udm88J+A+3VIc/7eCg2FH/icDX7ptaQo08qK+NdtePnsPzO1tDke2xwcT1H9b2f26v1rwecD7Tx9zVSE9FjgU2JTosuj3ya3rittHmkWPr0tgAjBhkfaMikjUh1ZIFq0QDBKnamxedpG7WsJFyvfxYMsezE1V84GbNYCzAKzPVFaPoKmDEJWC5MfSuomu0QVCYBJKgcJpcchWi0CGllMsmHKDZig6BPSVhBetLjRMNAjskTKqaWnMolS+do26rHPrTLi3e3VO81c9Q/oNf5KEB2OixRzghoHSuTpWLrwyNfG2oLnN5IKY=
install:
- pip install mkdocs
- pip install mkdocs-material
- pip install python-markdown-math
script:
- git clean -f -d -x
after_success:
- git config user.name "Tanatloc-bot"
- git config user.email "contact@airthium.com"
- git remote add gh-token "https://${GH_TOKEN}@github.com/FreeFem/FreeFem-doc.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;
