sudo: false
language: python
env:
  global:
    secure: oyZV9nCKm1iZzbOMo5wYZZ6ApYZsuE2wFTM2e0tBsYDf80StA5O5zS0sznrSAaeLfu5fdPQQ9ugZz6P4P+weFiuhCZao3EcXBepVHv//GmEQQFwrpZcAqMM0PLOSLF7flAmIhgTk3mjJSUXIjSo1H95BaxS9aVWri5O15TdN91nP93EEgXe1V0UZ6gsjk+9oTPmN3014HwfigYVVq8NzEOgHAbRKWpQsgc0HSUlsT1cCXfP1YQDDf68nEowp+NGTs4KexwQ6q82NyF0PisW4/kkRSpQGwNRAOZSugogYpS2P0ycu3nJCvndckKM9bWdZ1xXwC8k0jTqJnQuKsv9jKr7vWQfWBc9qKbXaH1XiRtrneNLFrydGfzxREqaIpvk7UzEfWQQtbOPu4c+Bmn4ZxiwON6NWteKfS2Y45ndmqSQdFljzT/RgEtirROILk1jhoSoVXA4v5HAiN6W2WsyM9ikIbP/x5yDkv0a2dKZ9eP07BD5pW44Whk3gHuRaIcfBU7IeNnNqctxs8j1DIpBebfN7VPdx9Nl2vZtySKvufWKf6q6c8yopdHmxjA/NYuL4Rf+g5e44qg6DM608L2656X0S1jrhev3pmH92qDBOqQWwY6gwdFyFTvq2A7BYDAFS0srAOg3eHZE7YfioO7pbFgjw+oeCpHuyFsaRYp4NBmw=
install:
- pip install mkdocs
- pip install mkdocs-material
- pip install python-markdown-math
script:
- git clean -f -d -x
- mkdocs build
after_success:
- git config user.name "Travis CI"
- git config user.email "contact@airthium.com"
- git remote add ghtoken "https://tanatloc-bot:${GH_TOKEN}@github.com/FreeFem/FreeFem-doc.git";
- git fetch ghtoken && git fetch ghtoken gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name ghtoken;
