site_name: FreeFem++
pages:
  - Home: index.md
  - Documentation:
    - Home: documentation/index.md
  - Tutorials:
    - Home: tutorial/index.md
  - References:
    - Home: reference/index.md
    - Types: reference/types.md
    - Global variables: reference/global-variables.md
    - Quadrature formulae: reference/quadrature.md
    - Operators: reference/operators.md
    - Loops: reference/loops.md
    - I/O: reference/io.md
    - Functions: reference/functions.md
    - Examples: reference/examples.md
    - TODO: reference/TODO.md
  - Examples:
    - Home: examples/index.md
theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'images/favicon.png'
  logo: 'images/favicon.png'
  palette:
    primary: 'light blue'
    accent: 'light blue'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_HTMLorMML
  - mathjax-config.js
markdown_extensions:
  - codehilite:
      guess_lang: false
  - mdx_math
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - toc:
      permalink: '#'
  - admonition
extra:
    social:
      - type: 'github'
        link: 'https://github.com/FreeFem/FreeFem-doc'
repo_name: 'FreeFem++ on Github'
repo_url: 'https://github.com/FreeFem/FreeFem-doc'



