site_name: FreeFem++
pages:
  - Introduction: index.md
  - Download: introduction/download.md
  - Installation: introduction/installation.md
  - How to contribute?: introduction/Contributing.md
  - Citation: introduction/citation.md
  - TODO: introduction/TODO.md
  - Documentation:
    - Home: documentation/index.md
    - Some Notations: documentation/Notations.md
    - Mesh Generation: documentation/MeshGeneration.md
    - Finite Element: documentation/FiniteElement.md
    - Visualization: documentation/Visualization.md
    - Algorithms & Optimization: documentation/AlgorithmsOptimization.md
    - Parallelization: documentation/Parallelization.md
    - Plugins: documentation/Plugins.md
    - Developers: documentation/Developers.md
    - TODO: documentation/TODO.md
  - Language References:
    - Home: reference/index.md
    - Types: reference/Types.md
    - Global variables: reference/GlobalVariables.md
    - Quadrature formulae: reference/QuadratureFormulae.md
    - Operators: reference/Operators.md
    - Loops: reference/Loops.md
    - I/O: reference/IO.md
    - Functions: reference/Functions.md
    - External libraries: reference/ExternalLibraries.md
    - TODO: reference/TODO.md
  - Tutorials:
    - Getting started: tutorials/index.md
    - Poisson's equation: tutorials/Poisson.md
    - Classification of the equations: tutorials/EquationsClassification.md
    - Membrane: tutorials/Membrane.md
    - Heat Exchanger: tutorials/HeatExchanger.md
    - Acoustics: tutorials/Acoustics.md
    - Thermal Conduction: tutorials/ThermalConduction.md
    - Irrotational Fan Blade Flow and Thermal effects: tutorials/FanBlade.md
    - Pure convection, The rotating hill: tutorials/RotatingHill.md
    - The system of elasticity: tutorials/Elasticity.md
    - The system of Stokes for fluids: tutorials/Stokes.md
    - A projection Algorithm for the Navier-Stokes equations: tutorials/NavierStokesProjection.md
    - Newton method for the steady Navier-Stokes equations: tutorials/NavierStokesNewton.md
    - A large fluid problem: tutorials/ALargeFluidProblem.md
    - An example with complex numbers: tutorials/ComplexNumbers.md
    - Optimal control: tutorials/OptimalControl.md
    - A flow with shocks: tutorials/FlowWithShocks.md
    - Time dependent schema optimization for heat equations: tutorials/HeatEquationOptimization.md
    - A transient Stokes solver in matrix form: tutorials/TimeDependentStokes.md
    - Wifi Propagation: tutorials/WifiPropagation.md
    - Matlab / Octave Plots: tutorials/MatlabOctavePlot.md
    - TODO: tutorials/TODO.md
  - Examples:
    - Home: examples/index.md
    - TODO: examples/TODO.md
  - Models:
    - Home: models/index.md
    - Static problems: models/StaticProblems.md
    - Elasticity: models/Elasticity.md
    - Non-linear static problems: models/NonLinearStaticProblems.md
    - Eigenvalue problems: models/EigenValueProblems.md
    - Evolution problems: models/EvolutionProblems.md
    - Navier-Stokes equations: models/NavierStokesEquations.md
    - Variational inequality: models/VariationalInequality.md
    - Domain decomposition: models/DomainDecomposition.md
    - Fluid-Structure coupled problem: models/FluidStructureCoupledProblem.md
    - Transmission problem: models/TransmissionProblem.md
    - Free boundary problem: models/FreeBoundaryProblem.md
    - Non-linear elasticity: models/NonLinearElasticity.md
    - Compressible Neo-Hookean materials: models/CompressibleNeoHookeanMaterials.md
    - Whispering gallery modes: models/WhisperingGalleryModes.md
    - TODO: models/TODO.md

theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'images/favicon.png'
  logo: 'images/favicon.png'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
  - mathjax-config.js

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - mdx_math
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: '#'
  - admonition
  - pymdownx.superfences
  - pymdownx.progressbar

extra:
    social:
      - type: 'github'
        link: 'https://github.com/FreeFem/FreeFem-doc'

repo_name: 'FreeFem++ on Github'
repo_url: 'https://github.com/FreeFem/FreeFem-doc'
