site_name: FreeFem++
pages:
  - Introduction: index.md
  - Download: introduction/download.md
  - Installation: introduction/installation.md
  - Documentation:
    - Home: documentation/index.md
  - Language References:
    - Home: reference/index.md
    - Types: reference/types.md
    - Global variables: reference/global-variables.md
    - Quadrature formulae: reference/quadrature.md
    - Operators: reference/operators.md
    - Loops: reference/loops.md
    - I/O: reference/io.md
    - Functions: reference/functions.md
    - Examples: reference/examples.md
    - TODO: reference/TODO.md
  - Tutorials:
    - Getting started: tutorial/index.md
    - Poisson's equation: tutorial/poisson.md
    - Membrane: tutorial/membrane.md
    - Heat Exchanger: tutorial/heat_exchanger.md
    - Acoustics: tutorial/acoustics.md
    - Thermal Conduction: tutorial/thermal_conduction.md
    - Irrotational Fan Blade Flow and Thermal effects: tutorial/fan_blade_flow.md
  - Examples:
    - Home: examples/index.md

theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'images/favicon.png'
  logo: 'images/favicon.png'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
  - mathjax-config.js



markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - mdx_math
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: '#'
  - admonition

extra:
    social:
      - type: 'github'
        link: 'https://github.com/FreeFem/FreeFem-doc'

repo_name: 'FreeFem++ on Github'
repo_url: 'https://github.com/FreeFem/FreeFem-doc'



