site_name: FreeFem++
pages:
  - Introduction: index.md
  - Download: introduction/download.md
  - Installation: introduction/installation.md
  - Documentation:
    - Home: documentation/index.md
  - Language References:
    - Home: reference/index.md
    - Types: reference/types.md
    - Global variables: reference/global-variables.md
    - Quadrature formulae: reference/quadrature.md
    - Operators: reference/operators.md
    - Loops: reference/loops.md
    - I/O: reference/io.md
    - Functions: reference/functions.md
    - Examples: reference/examples.md
    - (TODO) TODO: reference/TODO.md
  - Tutorials:
    - Getting started: tutorial/index.md
    - Poisson's equation: tutorial/poisson.md
    - Membrane: tutorial/membrane.md
    - Heat Exchanger: tutorial/heat_exchanger.md
    - Acoustics: tutorial/acoustics.md
    - (TODO) Thermal Conduction: tutorial/thermal_conduction.md
    - (TODO) Irrotational Fan Blade Flow and Thermal effects: tutorial/fan_blade_flow.md
    - (TODO) Pure convection, The rotating hill: tutorial/rotating_hill.md
    - (TODO) The system of elasticity: tutorial/elasticity_system.md
    - (TODO) The system of Stokes for fluids: tutorial/stokes_for_fluid_system.md
    - (TODO) A projection Algorithm for the Navier-Stokes equations: tutorial/navier_stokes_projection.md
    - (TODO) Newton method for the steady Navier_Stokes equations: tutorial/newton_method_navier_stokes.md
    - (TODO) A large fluid problem: tutorial/large_fluid_problem.md
    - (TODO) An example with complex numbers: tutorial/complex_numbers.md
    - (TODO) Optimal control: tutorial/optimal_control.md
    - (TODO) A flow with shocks: tutorial/flow_with_shocks.md
    - (TODO) Classifications of the equations: tutorial/equations_classification.md
    - (TODO) Time dependent schema optimization for heat equations: tutorial/heat_equation_optimization.md
    - (TODO) A transient Stokes solver in matrix form: tutorial/transient_stokes_solver_matrix.md
  - Examples:
    - Home: examples/index.md
    - (TODO) Commands for mesh generation: examples/commands_mesh_generation.md

theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'images/favicon.png'
  logo: 'images/favicon.png'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
  - mathjax-config.js



markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - mdx_math
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: '#'
  - admonition
  - pymdownx.superfences

extra:
    social:
      - type: 'github'
        link: 'https://github.com/FreeFem/FreeFem-doc'

repo_name: 'FreeFem++ on Github'
repo_url: 'https://github.com/FreeFem/FreeFem-doc'



